/*
 * SPDX-License-Identifier: MIT
 *
 * Maps INPUT_VIRTUAL_SYM_* codes (0x00–0x3D) to LV_SYMBOL_* string pointers.
 * Indexed by (code - INPUT_VIRTUAL_SYM_BASE); entries outside range return LV_SYMBOL_DUMMY.
 */

#pragma once

#include <lvgl.h>
#include <dt-bindings/xiaord/input_codes.h>

static const char *const s_sym_table[] = {
	[INPUT_VIRTUAL_SYM_BULLET        - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BULLET,
	[INPUT_VIRTUAL_SYM_AUDIO         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_AUDIO,
	[INPUT_VIRTUAL_SYM_VIDEO         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_VIDEO,
	[INPUT_VIRTUAL_SYM_LIST          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_LIST,
	[INPUT_VIRTUAL_SYM_OK            - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_OK,
	[INPUT_VIRTUAL_SYM_CLOSE         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_CLOSE,
	[INPUT_VIRTUAL_SYM_POWER         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_POWER,
	[INPUT_VIRTUAL_SYM_SETTINGS      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_SETTINGS,
	[INPUT_VIRTUAL_SYM_HOME          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_HOME,
	[INPUT_VIRTUAL_SYM_DOWNLOAD      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_DOWNLOAD,
	[INPUT_VIRTUAL_SYM_DRIVE         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_DRIVE,
	[INPUT_VIRTUAL_SYM_REFRESH       - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_REFRESH,
	[INPUT_VIRTUAL_SYM_MUTE          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_MUTE,
	[INPUT_VIRTUAL_SYM_VOLUME_MID    - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_VOLUME_MID,
	[INPUT_VIRTUAL_SYM_VOLUME_MAX    - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_VOLUME_MAX,
	[INPUT_VIRTUAL_SYM_IMAGE         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_IMAGE,
	[INPUT_VIRTUAL_SYM_TINT          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_TINT,
	[INPUT_VIRTUAL_SYM_PREV          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_PREV,
	[INPUT_VIRTUAL_SYM_PLAY          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_PLAY,
	[INPUT_VIRTUAL_SYM_PAUSE         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_PAUSE,
	[INPUT_VIRTUAL_SYM_STOP          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_STOP,
	[INPUT_VIRTUAL_SYM_NEXT          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_NEXT,
	[INPUT_VIRTUAL_SYM_EJECT         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_EJECT,
	[INPUT_VIRTUAL_SYM_LEFT          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_LEFT,
	[INPUT_VIRTUAL_SYM_RIGHT         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_RIGHT,
	[INPUT_VIRTUAL_SYM_PLUS          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_PLUS,
	[INPUT_VIRTUAL_SYM_MINUS         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_MINUS,
	[INPUT_VIRTUAL_SYM_EYE_OPEN      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_EYE_OPEN,
	[INPUT_VIRTUAL_SYM_EYE_CLOSE     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_EYE_CLOSE,
	[INPUT_VIRTUAL_SYM_WARNING       - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_WARNING,
	[INPUT_VIRTUAL_SYM_SHUFFLE       - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_SHUFFLE,
	[INPUT_VIRTUAL_SYM_UP            - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_UP,
	[INPUT_VIRTUAL_SYM_DOWN          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_DOWN,
	[INPUT_VIRTUAL_SYM_LOOP          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_LOOP,
	[INPUT_VIRTUAL_SYM_DIRECTORY     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_DIRECTORY,
	[INPUT_VIRTUAL_SYM_UPLOAD        - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_UPLOAD,
	[INPUT_VIRTUAL_SYM_CALL          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_CALL,
	[INPUT_VIRTUAL_SYM_CUT           - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_CUT,
	[INPUT_VIRTUAL_SYM_COPY          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_COPY,
	[INPUT_VIRTUAL_SYM_SAVE          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_SAVE,
	[INPUT_VIRTUAL_SYM_BARS          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BARS,
	[INPUT_VIRTUAL_SYM_ENVELOPE      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_ENVELOPE,
	[INPUT_VIRTUAL_SYM_CHARGE        - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_CHARGE,
	[INPUT_VIRTUAL_SYM_PASTE         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_PASTE,
	[INPUT_VIRTUAL_SYM_BELL          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BELL,
	[INPUT_VIRTUAL_SYM_KEYBOARD      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_KEYBOARD,
	[INPUT_VIRTUAL_SYM_GPS           - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_GPS,
	[INPUT_VIRTUAL_SYM_FILE          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_FILE,
	[INPUT_VIRTUAL_SYM_WIFI          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_WIFI,
	[INPUT_VIRTUAL_SYM_BATTERY_FULL  - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BATTERY_FULL,
	[INPUT_VIRTUAL_SYM_BATTERY_3     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BATTERY_3,
	[INPUT_VIRTUAL_SYM_BATTERY_2     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BATTERY_2,
	[INPUT_VIRTUAL_SYM_BATTERY_1     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BATTERY_1,
	[INPUT_VIRTUAL_SYM_BATTERY_EMPTY - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BATTERY_EMPTY,
	[INPUT_VIRTUAL_SYM_USB           - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_USB,
	[INPUT_VIRTUAL_SYM_BLUETOOTH     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BLUETOOTH,
	[INPUT_VIRTUAL_SYM_TRASH         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_TRASH,
	[INPUT_VIRTUAL_SYM_BACKSPACE     - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_BACKSPACE,
	[INPUT_VIRTUAL_SYM_SD_CARD       - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_SD_CARD,
	[INPUT_VIRTUAL_SYM_NEW_LINE      - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_NEW_LINE,
	[INPUT_VIRTUAL_SYM_DUMMY         - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_DUMMY,
	[INPUT_VIRTUAL_SYM_EDIT          - INPUT_VIRTUAL_SYM_BASE] = LV_SYMBOL_EDIT,
};

static inline const char *sym_code_to_str(uint16_t code)
{
	uint16_t idx = code - INPUT_VIRTUAL_SYM_BASE;

	if (idx >= ARRAY_SIZE(s_sym_table) || s_sym_table[idx] == NULL) {
		return LV_SYMBOL_DUMMY;
	}
	return s_sym_table[idx];
}
